name: hyenadna
type: hyenadna
hidden_size: 256
cond_dim: 64
length: ${model.length}  # Same length as diffusion model
n_layer: 8  # Number of HyenaDNA layers
scale_by_sigma: False
dropout: 0.1
num_classes: ${data.num_classes}
pooling: mean
hyena_model_name_or_path: "LongSafari/hyenadna-small-32k-seqlen"
